// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Configuration Supabase - Utilise les variables d'environnement ou les valeurs par défaut
// Compatible avec Electron et Vite
const getEnvVar = (key: string, defaultValue: string): string => {
  // Essayer import.meta.env (Vite)
  if (import.meta.env[key]) return import.meta.env[key];
  // Essayer process.env (Electron/Node)
  if (typeof process !== 'undefined' && process.env && process.env[key]) {
    return process.env[key];
  }
  return defaultValue;
};

const SUPABASE_URL = getEnvVar('VITE_SUPABASE_URL', 'https://vwecfxtgqyuydhlvutvg.supabase.co');
const SUPABASE_PUBLISHABLE_KEY = getEnvVar('VITE_SUPABASE_ANON_KEY', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3ZWNmeHRncXl1eWRobHZ1dHZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3MzY5OTQsImV4cCI6MjA3NzMxMjk5NH0.6oZR5-NV8XDxQgIJlm4R7zarf5kFg0-tN26ko_kpye8');

// Validation de l'URL
function isValidUrl(string) {
  try {
    new URL(string);
    return true;
  } catch (_) {
    return false;
  }
}

// Vérifier que l'URL est valide avant de créer le client
if (!isValidUrl(SUPABASE_URL)) {
  console.error('❌ URL Supabase invalide:', SUPABASE_URL);
  throw new Error('URL Supabase invalide');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Vérification des variables d'environnement
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ Variables d\'environnement Supabase manquantes!');
  console.log('Assurez-vous d\'avoir configuré:');
  console.log('- VITE_SUPABASE_URL');
  console.log('- VITE_SUPABASE_ANON_KEY');
} else {
  console.log('✅ Configuration Supabase chargée');
  console.log('URL:', SUPABASE_URL);
  console.log('Clé:', SUPABASE_PUBLISHABLE_KEY.substring(0, 20) + '...');
}

// Créer et exporter le client Supabase avec options de configuration
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  },
  db: {
    schema: 'public'
  },
  global: {
    headers: {
      'x-client-info': 'supabase-js-web'
    }
  }
});